name: Property Management System CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- Frontend CI Steps ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      # --- Frontend CD Step (Deployment) ---
      # Add your deployment logic here. This part will only run
      # on pushes to the 'main' branch, ensuring only
      # production-ready code is deployed.
      #
      # Example for Vercel:
      # - name: Deploy to Vercel
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     npm install --global vercel
      #     vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      #     vercel build
      #     vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
